# Generated by Django 5.2.12 on 2026-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Keyword')),
                ('app_name', models.CharField(max_length=100, verbose_name='App Name')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Path')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Keyword')),
                ('response', models.TextField(verbose_name='Say')),
            ],
        ),
    ]
